### ISSUE TITLE
solution please

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [prodigysml/Dr.-Watson#13]
java.lang.Exception: Failed to open Jython JAR file
	at burp.et5.<init>(Unknown Source)
	at burp.dgg.a(Unknown Source)
	at burp.ld.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by xYantix** [comment]
Hi @gauravdrago - This error suggests that Burp is having trouble with the Jython .JAR file rather than the Dr.-Watson Bapp. 

Can you please confirm which version of the Jython Standalone .jar you're using as well as confirming your Burp is configured following this guide? https://www.gracefulsecurity.com/burp-suite-extensions-installing-jython-and-adding-an-extension/

**Comment by GDATTACKER-RESEARCHER** [comment]
I have downloaded the latest one yesterday.

**Comment by xYantix** [comment]
Can you please upload a screenshot from your Burp Suite > Extender > Options tab?

**Comment by GDATTACKER-RESEARCHER** [comment]
Jython 2.7.1

**Comment by xYantix** [comment]
Can you please upload something like this? Also, please see this post - https://support.portswigger.net/customer/portal/questions/17624925-failed-to-load-python-interpreter-from-jython-jar-file 

It might be worth downloading Jython again **Make sure it's the Standalone Version**

![image](https://user-images.githubusercontent.com/3001014/68648052-63eea080-055a-11ea-9a87-c1e8cb0476c4.png)

**Comment by GDATTACKER-RESEARCHER** [comment]
yeah it's standalone but thier is some other issue i guess sorted now
thanks for quick responding.

**Comment by xYantix** [comment]
Glad to hear it's working now. Reach out if there are any other issues though! 😄
