### ISSUE TITLE
"Asset Discovered" duplicates findings on different pages

### ISSUE THREAD

**Issue by 0x90n** [prodigysml/Dr.-Watson#6]
The "Asset Discovered" function doesn't duplicate findings (e.g. test.beta.com) on the same page (e.g. /finance.html) but replicates duplicate findings across different pages (e.g. /contact.html).

Perform a python check that, similar to the finding on the same page, doesn't push a result to a duplicate finding on a separate/unique page. If you'd like a code example, I can add one.

This will reduce false positives, clutter and only result in unique findings.

Also - might be worth creating an inbuilt blacklist of certain non-important asset discoveries.

e.g:

*schemas*
*w3.org*
*macromedia*

**Comment by prodigysml** [comment]
Thanks for submitting this issue. We were able to reproduce it. The reason we actually do raise this as a multiple findings is the path for things like URLs. An example is, we can raise an external domain (like google.com), in /admin and /user, but the path may be different. So we try to raise it in both places, allowing the tester to be aware of all locations. Would that justification help, or is it better to de-duplicate entirely?

**Comment by xYantix** [comment]
I think entirely de-duplicating it may result in things being missed.

**Comment by prodigysml** [comment]
I believe this has been justified now. Should anyone have any further issues, please feel free to re-open.
