### ISSUE TITLE
Add support for flagging HTML comments 

### ISSUE THREAD

**Issue by xYantix** [prodigysml/Dr.-Watson#8]
There are often pieces of information added within comments. It may be worth adding a check to alert if something is discovered within these tags. eg.

**Comment by prodigysml** [comment]
We do check for information within HTML comments. Are you referring to raising that there are HTML comments in general too?

**Comment by xYantix** [comment]
I meant searching within the comments but I must have misinterpreted the way it operated. Didn't think you were searching them. 

There _might_ be value in raising that there are comments in general but you'll run into weird issues if a site uses knockout.js as I believe that library actually uses comments for things. Probably worth just closing this one out :)

**Comment by prodigysml** [comment]
Awesome! Thanks for raising this @xYantix! Due to the way we do regex searches, we already do search comments.
